### ISSUE TITLE
Thoughts?

### ISSUE THREAD

**Issue by bionictoothpick** [xSplasher/TwitchLichessBot#2]
node ChatPlaysChess.js
listening on port :7777
######## there's no ongoing at the moment => getongoinggameID
node:internal/process/promises:265
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Not connected to server.".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

**Comment by xSplasher** [comment]
nothing to worry about, the bot is working as intended.
